### ISSUE TITLE
Typo field name ups_abmtemp should be ups_ambtemp

### ISSUE THREAD

**Issue by jab60** [Cacti/plugin_apcupsd#6]
cacti log error DBCALL ERROR: SQL Save on table 'apcupsd_ups_stats': Column 'ups_ambtemp' does not exist, unable to save!

In setup.php on field creation table apcupsd_ups_stats
The field ups_ambtemp is typed as ups_a**bm**temp

**Comment by TheWitness** [comment]
This is resolved now.  Thanks for reporting it.
