### ISSUE TITLE
Check poller_apcupsd.php

### ISSUE THREAD

**Issue by Onix-Xino** [Cacti/plugin_apcupsd#7]
Is it possible to add in the script a check for the full path to apcaccess?
Or ways to search.
Something like bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

On line 310 in poller_apcupsd.php it is enough to provide the full path to the apcaccess command to report the status correctly => UP and to collect the data, which after assigning the available graphs should be drawn.
$command = 'apcaccess -u -h ' . $ups['hostname'] . ':' . $ups['port']; 
$command = '/usr/sbin/apcaccess -u -h ' . $ups['hostname'] . ':' . $ups['port'];

**Comment by TheWitness** [comment]
I think this is resolved now.  It looks for the path in 3 different locations.
